default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>

development:
  <<: *default
  database: capstone_api_development

test:
  <<: *default
  database: capstone_api_test

production:
  <<: *default
  database: capstone_api_production
  username: capstone_api
  password: <%= ENV["CAPSTONE_API_DATABASE_PASSWORD"] %>